version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1 # Invoke the Heroku orb
  browser-tools: circleci/browser-tools@1.0.0

workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14.1

    working_directory: ~/repo

    steps:
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test